config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, :comments, :posts

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :conversations do
    resources :messages
  end

  post '/comments/create' => 'comments#create'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"

  has_many :messages

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id, recipient_id) do
  where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
 end

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :posts
  has_many :comments

  has_many :messages, foreign_key: :sender
  has_many :messages, foreign_key: :receiver
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def require_login
    redirect_to login_path unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :require_login

  def new
    @comment = Comment.new
  end

  def create
      @comment = Comment.new(comment_params)
      @comment.user_id = current_user.id
      if @comment.save
        render partial: 'show_jq', layout: false, locals:{comment: @comment}
        else
          flash[:notice] = "Please complete all fields."
      end
    end


  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :require_login
  
  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end
    redirect_to conversation_messages_path(@conversation)
  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController


  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    @message = @conversation.messages.new
  end


  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end



  private

  def message_params
    params.require(:message).permit(:content, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper

  before_action :require_login
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]



  def index
    @posts = Post.all.reverse_order
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to '/posts'
    else
      flash[:notice] = "Please complete all fields."
   end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
    @comments = Comment.all.reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
  @post = Post.find(params[:id])

    if time_not_expired
      if @post.update_attributes(post_params)
        redirect_to post_path
    else
      flash[:notice] = "Please complete all fields."
      end
    end
  end

  def destroy
    @post = Post.find params[:id]
    @post.destroy
    redirect_to '/posts'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :img_url)
  end

  def set_user
    @user = current_user
  end

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to user_path(current_user.id)
    end
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/posts'
    else
      flash[:notice] = "Invalid username or password."
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]
 before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to '/'
    else
      flash[:notice] = "Please complete all fields."
      redirect_to '/users/new'
    end
  end

  def show
    set_user
  end



  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar_url)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_s3_direct_post
    @s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def show_messages?
    conversation.recipient == user || conversation.sender == user
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def time_not_expired
    current_user == @post.user && Time.now.in_time_zone("London") - @post.created_at <= 3600
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_show.html.erb
<p><%=comment.content%></p>
<h6>Posted by <%=comment.user.first_name%> at <%=comment.created_at%></h6>

app/views/comments/_show_jq.html.erb
<p><%=@comment.content%></p>
<h6>Posted by <%=@comment.user.first_name%> at <%=@comment.created_at%></h6>

app/views/conversations/index.html.erb
<div class="middle">
<h1>Direct Messages</h1>

<% @conversations.each do |conversation| %>
  <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
   <% if conversation.sender_id == current_user.id %>
     <% recipient = User.find(conversation.recipient_id) %>
   <% else %>
     <% recipient = User.find(conversation.sender_id) %>
   <% end %>
   <%= link_to recipient.first_name, conversation_messages_path(conversation)%><br>
  <% end %>
 <% end %>


 <h3>All Users</h3>

<ul>
  <% @users.each do |user| %>
   <% if user.id != current_user.id %>
<li><%= user.first_name %> <%= link_to "Message me!", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post"%></li>
 <% end %>
<% end %>
<ul>
</div>

app/views/messages/index.html.erb
<div class="middle">
<h1>Direct Messages</h1>

 <% @messages.each do |message| %>
  <% if message.content %>
  <div class="well well-lg">
   <% user = User.find(message.user_id) %>
     <% if message.user.avatar_url %>
  <%=image_tag(message.user.avatar_url, :width => 50, :height => 50, :alt => "glyphicon glyphicon-user")%>
  <%end %>
  <strong><%= user.first_name.upcase %>:</strong>
   <%= message.content%><br>
 </div>
 <% end %>
<% end %>

<%= bootstrap_form_for [@conversation, @message], url: {action: "create"} do |f| %>
 <div class=”field”>
   <%= f.text_area :content %>
 </div>
 <%= f.hidden_field :user_id, value: current_user.id %>
 <div>
   <%= f.submit label: "Send" %>
 </div>
<% end %>

<script>
$(function() {
  // Emoji picker
  $('#message_content').emojiPicker({
    height: '300px',
    width:  '450px'
  });
});
</script>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
        this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Top Posts</h1>

<a id="create" href="/posts/new">Create New Post</a>


<div class="post-photos">
  <% @posts.each do |post| %>
  <a class="post-a" href="/posts/<%=post.id%>">
    <figure>
      <img src="<%=post.img_url%>" alt=" ", width = 280, height= 240 />
      <figcaption>
        <%= post.title.upcase %>
      </figcaption>
    </figure>
  </a>
  <%end%>
</div>

app/views/posts/new.html.erb
<div class="middle">
<h1>New Post</h1>

<%= bootstrap_form_for(@post, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
  <%= f.text_field :title, hide_label: true, placeholder: "Title"  %>
  <%= f.text_area :content, hide_label: true, placeholder: "Body"  %>
  <%= f.file_field :img_url, label: "Cover Picture" %>
  <%= f.submit "Post" %>
<% end %>

<script>
$(function() {
  // Emoji picker
  $('#post_title').emojiPicker({
    height: '300px',
    width:  '450px'
  });
});
$(function() {
  // Emoji picker
  $('#post_content').emojiPicker({
    height: '300px',
    width:  '450px'
  });
});
</script>
</div>

app/views/posts/show.html.erb
<div class="middle">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @post.title %></h3>
    </div>
    <div class="panel-body">
      <%=@post.content %>
    </div>
  </div>
  <% if time_not_expired%>
    <a href="/posts/<%=@post.id%>/edit">Edit</a>
  <%end%>
  <h6>Posted by <%=@post.user.first_name%> at <%=@post.created_at.in_time_zone("Eastern Time (US & Canada)")%>
    <%if @post.user == current_user%>
    <%= link_to 'Delete', @post, :confirm => 'Are you sure?',
                                   :method => :delete %>
    <%end%>
  <div class="fb-share-button" data-href="http://grrrl.herokuapp.com/posts" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fgrrrl.herokuapp.com%2Fposts&amp;src=sdkpreparse">Share</a>
  </div>
</h6>
<div class="commentdiv input-group">
  <%= form_for @comment, url: '/comments' do |f| %>
    <p>
      <%= f.text_area :content %>
      <%= f.hidden_field :post_id, value: @post.id %>
    </p>
    <p class="btn">
      <%= f.submit %>
    </p>
  <% end %>
</div>

<div class="comment">
<% if @comments %>
    <% @comments.each do |comment| %>
    <%= render partial: '/comments/show', locals: { comment: comment} %>
  <%end%>
<%end%>
</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
<div class="field">
  <%= f.label :avatar_url %><br>
  <%= f.file_field :avatar_url %>
</div>
<%end%>

app/views/users/new.html.erb
<div class = "middle">
<h1>Register</h1>
<%= bootstrap_form_for(@user, html: { class: 'directUpload', data: { 'form-data' => (@s3_direct_post.fields), 'url' => @s3_direct_post.url, 'host' => URI.parse(@s3_direct_post.url).host } }) do |f| %>
<%= f.text_field :first_name, hide_label: true, placeholder: "First Name" %>
<%= f.text_field :last_name, hide_label: true, placeholder: "Last Name" %>
<%= f.email_field :email, hide_label: true, placeholder: "Email" %>
<%= f.password_field :password, hide_label: true, placeholder: "Password" %>
<%= f.file_field :avatar_url, label: "Profile Picture" %>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/users/show.html.erb
<h1>Posts by <%=@user.first_name%></h1>

<%@user.posts.each do |post|%>
<h3> <a href="/posts/<%=post.id%>"><%=post.title%></a></h3>
<%end%>

app/views/welcome/index.html.erb
<div class="tophome">
<div class="circle">Grrrl</div>
</div>

  <div class="row">
    <div class="col-xs-12 description" >
      <span class="glyphicon glyphicon-star-empty star1" aria-hidden="true"></span>
      <span class="glyphicon glyphicon-star-empty star1" aria-hidden="true"></span>
      <span class="glyphicon glyphicon-star-empty star1" aria-hidden="true"></span>
      <div class="square">
        <h1> Reviews of products and services that girls care about.<br>  Written by feminists, for feminists. </h1>
      </div>
      <span class="glyphicon glyphicon-star-empty star2" aria-hidden="true"></span>
      <span class="glyphicon glyphicon-star-empty star2" aria-hidden="true"></span>
      <span class="glyphicon glyphicon-star-empty star2" aria-hidden="true"></span>
     </div>
  </div>


<div class="row">
<img id="homepageimage" src="http://a4.files.fashionista.com/image/upload/c_fit,cs_srgb,dpr_1.0,h_1200,q_80,w_1200/MTQwNzI1OTAxMzM4ODc5Nzg3.jpg" alt="" />

</div>